#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Removes default NGINX config file
rm /etc/nginx/sites-enabled/default
# Configs NGINX to listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart NGINX
service nginx restart

